# Generated by Django 3.2.16 on 2022-11-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lantitude', models.DecimalField(decimal_places=2, max_digits=5, max_length=10)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, max_length=10)),
                ('descreption', models.TextField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
