# Generated by Django 3.2.15 on 2022-11-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgence',
            name='lantitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, max_length=10),
        ),
        migrations.AlterField(
            model_name='urgence',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, max_length=10),
        ),
    ]
