# Generated by Django 3.2.15 on 2022-11-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgence', '0002_auto_20221115_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgence',
            name='descreption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
