# Generated by Django 3.2.15 on 2022-11-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgence', '0003_alter_urgence_descreption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgence',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='description'),
        ),
    ]
